### PR TITLE
Really update for 0.15

### PR DESCRIPTION
**Pull request by aforemny**
Further testing revealed that changes were not compatible with Chrome. I reverted changes back to the previous version. This seems to be more robust, as examples are now working in both Firefox and Chrome.

Apologies for the faulty PR!

Examples are updated in aforemny/elm-lang.org@1756758.

### CODE REVIEW

**Comment by evancz** [comment]
Should the error type match the HTTP errors from elm-http? I don't have a strong intuition for this.

**Comment by aforemny** [comment]
I think it should not necessarily, because this patch does not use the elm-http module nor XMLHttpRequest.

I will find out more about Javascript's Image.onerror function and make the WebGL's error type more expressive.

**Comment by aforemny** [comment]
I cannot find any documentation on JavaScript's Image.onerror function. I read somewhere that implementation is browser specific, so I'm tending to leave Error an opaque type.

In practice I cannot chain WebGL.loadTexture tasks with Http tasks because they differ on the error type. I found the solution load WebGL and Http resources in separate tasks OK and one could work around that with Task.onError.

I'd appreciate any suggestion. Otherwise I think this should be merged, as it works better than my previous "fix". :)

**Comment by johnpmayer** [comment]
Yep, will need to wait for blob support to use the standard Http error types

**Pull request merged**
