### PR TITLE
Default texture filters to GL_NEAREST

### PR DESCRIPTION
**Pull request by aforemny**
I would like to argue that the default min/mag filters should be changed from ```GL_LINEAR``` to ```GL_NEAREST```.

The motivation is that ```GL_NEAREST``` is more flexible: For textures it gives you a pixelated look. Something which is not possible with ```GL_LINEAR``` filters. If you want filtering you should write it yourself in your fragment shader by evaluating your color function for ```n``` pixels with offsets ```delta_1…delta_n```, and then average them for the fragment color.

Also, if you treat your textures as height maps you would want to get the accurate height information of that pixel, and not some average of pixels as it is the case with ```GL_LINEAR```.

Is this convincing?

Would an example be appreciated that shows how to do filtering with the default being no filtering?

### CODE REVIEW

**Comment by johnpmayer** [comment]
I'd rather keep LINEAR the default, as it feels more beginner friendly, and
make it configurable if you need it. So a new enum and a new 'raw' function
for creating textures.

**Comment by aforemny** [comment]
I don't necessarily agree that ```GL_LINEAR``` is more beginner friendly, because I image a beginner expecting ```texture2D``` to return the requested pixel's color exactly. Since with filtering it usually does not, there is something going on which is not immediately obvious. So, I think with ```GL_NEAREST``` as the default it is easier to reason about why your texture does not look the way you expected it, and thus implement filtering in the shader (or use a ```loadTextureFiltered```) function.

Never the less, is what I implemented now the way you would like to go? :)

**Comment by johnpmayer** [comment]
Taking a look at this, I think I want to go with some sort of pattern like the below to minimize the API impact. I think I can refactor this myself. Bucketing in next release.

``` Elm
defaultOptions : TextureOptions
loadTextureWithConfig : TextureOptions -> String -> Task Error Texture
loadTexture = loadTextureWithConfig defaultOptions 
```

**Comment by aforemny** [comment]
Great! Cannot wait to see the next release! :))

I found myself having to disable depth test and enabling blending. Do you plan on exposing this to the API as well, or could I open an issue to make a stand to get this functionality into the next release? :)

**Pull request merged**
